version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    working_directory: ~/workspace
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_API_LEVEL: 26
      EMULATOR_API_LEVEL: 22
      ANDROID_BUILD_TOOLS_VERSION: 27.0.3
      ANDROID_ABI: armeabi-v7a
      ANDROID_TAG: google_apis
      ANDROID_TARGET: android-$ANDROID_API_LEVEL
      ADB_INSTALL_TIMEOUT: 20 # minutes (2 minutes by default)
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator
          command: circle-android wait-for-boot
          environment:
            TERM: dumb
      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb
      - run:
          name: Unit testing
          command: ./gradlew test
          environment:
            TERM: dumb
#      - run:
#          name: Build
#          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest --stacktrace